name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri ${{ env.DALAMUD_ARCHIVE_URL }} -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        env:
          DALAMUD_ARCHIVE_URL: ${{ vars.DALAMUD_ARCHIVE_URL || 'https://goatcorp.github.io/dalamud-distrib/latest.zip' }}

      - name: Restore Project
        run: dotnet restore --locked-mode

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ModOrganizer
          path: |
             ModOrganizer\bin\x64\Release\*
             !ModOrganizer\bin\x64\Release\ModOrganizer\*

      - name: Run Tests
        run: .\ModOrganizer.Tests\bin\Release\ModOrganizer.Tests.exe --coverage --coverage-output ${{ github.sha }}.cobertura.xml --coverage-output-format cobertura 

      - name: Upload Tests Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ModOrganizer.Tests
          path: ModOrganizer.Tests\bin\Release\TestResults\${{ github.sha }}.cobertura.xml

      - name: Upload Tests Coverage
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@v5
        with:
          files: ModOrganizer.Tests\bin\Release\TestResults\${{ github.sha }}.cobertura.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}




