name: Build and Release

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  Build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri ${{ env.DALAMUD_ARCHIVE_URL }} -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        env:
          DALAMUD_ARCHIVE_URL: ${{ vars.DALAMUD_ARCHIVE_URL || 'https://goatcorp.github.io/dalamud-distrib/latest.zip' }}

      - name: Restore Project
        run: dotnet restore --locked-mode

      - name: Build Project
        run: dotnet build --configuration Release -p:AssemblyVersion=${{ github.ref_name }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ModOrganizer
          path: |
             ModOrganizer\bin\x64\Release\*
             !ModOrganizer\bin\x64\Release\ModOrganizer\*

      - name: Run Tests
        run: .\ModOrganizer.Tests\bin\Release\net10.0-windows\ModOrganizer.Tests.exe --coverage --coverage-output-format cobertura --coverage-output ${{ github.sha }}.cobertura.xml

      - name: Upload Tests Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ModOrganizer.Tests
          path: ModOrganizer.Tests\bin\Release\net10.0-windows\TestResults\${{ github.sha }}.cobertura.xml

      - name: Upload Tests Coverage
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@v5
        with:
          name: ${{ github.ref_name }}
          files: ModOrganizer.Tests\bin\Release\net10.0-windows\TestResults\${{ github.sha }}.cobertura.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ModOrganizer\bin\x64\Release\ModOrganizer\latest.zip
          asset_name: ModOrganizer.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}